/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 01-09-2023
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class JSONToolkit extends FileToolkit{
    public override void setRoot(id rootId){

    }
    public override void addChild(Object parent, id userRoleId){

    }
    public override Document genDoc(){
        return null;
    }
    public override String getFileName(){
        return null;
    }
}
