name: Deploy Action
run-name: ${{ github.actor }} Deployment Workflow
on:
  workflow_call:
    inputs:
      var:
        required: true
        type: string
      username:
        required: true
        type: string
jobs:
  deployment-job:
    runs-on: ubuntu-latest
    environment: roles_prod
    steps:
      - run: "echo Environment ${{ inputs.var }}"
      - run: "echo AUTH URL ${{ secrets.AUTH_URL }}"
      - run: "echo username ${{ inputs.username }}"
      - uses: actions/checkout@v3
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_URL }}
      - run: sfdx auth list
      - run: sfdx plugins:install @salesforce/sfdx-scanner 
      - run: sfdx scanner run -t ./ > ./actionslogfiles/scanner_results.txt
      - run: sfdx force:source:deploy -u ${{ inputs.username }} -x ./manifest/package.xml > ./actionslogfiles/deploy_results.txt
