name: Deploy Action
run-name: ${{ github.actor }} is pushing changes to ${{ env.GITHUB_ENV }}
on:
  workflow_call:
    inputs:
      authurl:
        required: true
        type: string
jobs:
  deployment-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ inputs.authurl }}
      - run: sfdx plugins:install @salesforce/sfdx-scanner 
      - run: sfdx scanner run -t ./ > ./actionslogfiles/scanner_results.txt
      - run: sfdx force:source:deploy -x ./manifest/package.xml > ./actionslogfiles/deploy_results.txt
