name: test-github-actions
run-name: ${{ github.actor }} is testing Github Actions
on: push
jobs: 
  checkversion:
    runs-on: macos-latest
    steps:
      - uses: forcedotcom/salesforcedx-actions@master
      - run: sfdx --version
