name: test-github-actions
run-name: ${{ github.actor }} is testing Github Actions
on: push
jobs: 
  printhello:
    runs-on: macos-latest
    steps:
      - run: git --version
      - run: sfdx --version
