name: test-github-actions
run-name: ${{ github.actor }} is merging feature branch to master
on: 
  push:
    branches:
      - main
      - Github-Actions-Playground
jobs: 
  install_sfdx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTHURL }}
      - run: sfdx scanner run -t ./ > actionlogfiles/scanner_results.txt
      - run: sfdx force:source:deploy -c -x ./manifest/package.xml > actionlogfiles/validation_results.txt
