name: test-github-actions
run-name: ${{ github.actor }} is testing Github Actions
on: push
jobs: 
  checkversion:
    runs-on: macos-latest
    steps:
      - run: curl -o sfdx.pkg 'https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx.pkg'
      - run: sudo installer -pkg sfdx.pkg -target /
      - run: sfdx --version
