name: test-github-actions
run-name: ${{ github.actor }} is testing Github Actions
on: push
jobs: 
  install_sfdx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTHURL }}
      - run: sfdx force:source:retrieve -x ./manifest/package.xml
