name: deploy-to-production
run-name: ${{ github.actor}} pushing changes to production
on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - master
jobs: 
  merged_to_master:
    uses: ./.github/workflows/deployworkflow.yml
    with: 
      var: roles_prod
      username: kushal.basu@mindful-panda-2wtvls.com

