name: deploy-to-staging
run-name: ${{ github.actor}} pushing changes to production
on:
  pull_request:
    types:
      - closed
  push:
    branches:
      - staging
jobs: 
  merged_to_master:
    runs-on: ubuntu-latest
    environment: roles_prod
    steps:
      - uses: actions/checkout@v3
      - uses: sfdx-actions/setup-sfdx@v1
        with:
          sfdx-auth-url: ${{ secrets.AUTH_URL }}
      - run: sfdx auth list
      - run: sfdx plugins:install @salesforce/sfdx-scanner 
      - run: sfdx scanner run -t ./ > ./actionslogfiles/scanner_results.txt
      - run: sfdx force:source:deploy -x ./manifest/package.xml > ./actionslogfiles/deploy_results.txt

