name: action-playground
run-name: ${{ github.actor }} is merging feature branch to master
on:
  pull_request:
    types:
      - closed
jobs:
  merged_to_master:
    if: ${{ github.base_ref == 'master' }}
    environment: roles_prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  merged_to_dev:
    if: ${{ github.base_ref == 'dev' }}
    environment: roles_dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  merged_to_staging:
    if: ${{ github.base_ref == 'staging' }}
    environment: roles_staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
  call_workflow:
    if: |
      always()
      && contains(needs.*.result, 'success')
      && !contains(needs.*.result, 'failure')
    needs: [merged_to_master,merged_to_dev,merged_to_staging]
    uses: ./.github/workflows/deployworkflow.yml
    name: Initiate deployment workflow
    with:
      authurl: $environment.AUTH_URL